"""Central display name mapping for packages."""

PACKAGE_DISPLAY: dict[str, str] = {
    "com.google.android.youtube": "YouTube",
    "app.morphe.android.youtube": "YouTube",
    "com.google.android.apps.youtube.music": "YouTube Music",
    "app.morphe.android.apps.youtube.music": "YouTube Music",
    "com.reddit.frontpage": "Reddit",
    "com.reddit.frontpage.morphe": "Reddit",
    "com.chess": "Chess",
    "com.chess.prathxm": "Chess",
    "com.mgoogle.android.gms": "MicroG",
    "app.revanced.android.gms": "MicroG",
    "tv.twitch.android.app": "Twitch",
    "com.strava": "Strava",
    "com.google.android.apps.photos": "Google Photos",
    "com.microblink.photomath": "Photomath",
    "com.facebook.katana": "Facebook",
    "com.amazon.mp3": "Amazon Music",
    "com.bandcamp.android": "Bandcamp",
    "de.gmx.mobile.android.mail": "GMX Mail",
    "ginlemon.iconpackstudio": "Icon Pack Studio",
    "com.facebook.orca": "Messenger",
    "com.letterboxd.letterboxd": "Letterboxd",
    "com.nothing.smartcenter": "Nothing X",
    "jp.pxv.android": "Pixiv",
    "com.adguard.android": "AdGuard",
    "com.adobe.lrmobile": "Lightroom",
    "com.soundcloud.android": "SoundCloud",
    "pl.solidexplorer2": "Solid Explorer",
    "videoeditor.videorecorder.screenrecorder": "Screen Recorder",
    "ru.iiec.pydroid3": "PyDroid3",
    "com.myfitnesspal.android": "MyFitnessPal",
    "ch.protonvpn.android": "ProtonVPN",
    "com.amazon.avod.thirdpartyclient": "Prime Video",
    "com.duolingo": "Duolingo",
    "com.cricbuzz.android": "Cricbuzz",
    "com.google.android.apps.recorder": "Recorder",
    "com.microsoft.office.officelens": "Office Lens",
    "com.google.android.apps.magazines": "Google News",
    "com.github.android": "GitHub",
    # New apps from 166 expansion
    "com.adobe.photoshopmix": "Photoshop Mix",
    "com.amazon.mShop.android.shopping": "Amazon Shopping",
    "com.drinkplusplus.angulus": "Angulus",
    "com.myprog.hexedit": "HexEdit",
    "com.viber.voip": "Viber",
    "net.binarymode.android.irplus": "IRPlus",
    "nl.sanomamedia.android.nu": "NU.nl",
    "app.ttmikstories.android": "TTMik Stories",
    "bitpit.launcher": "Bitpit Launcher",
    "cn.ommiao.iconpacker": "Icon Packer",
    "cn.wps.moffice_eng": "WPS Office",
    "com.alltrails.alltrails": "AllTrails",
    "com.avocards": "Avocards",
    "com.bambuna.podcastaddict": "Podcast Addict",
    "com.bunpoapp": "Bunpo",
    "com.busuu.android.enc": "Busuu",
    "com.getmimo": "Mimo",
    "com.goodreads": "Goodreads",
    "com.hellochinese": "HelloChinese",
    "com.intsig.camscanner": "CamScanner",
    "com.lingodeer": "LingoDeer",
    "com.lyfta": "Lyfta",
    "com.merriamwebster": "Merriam Webster",
    "com.michaldrabik.showly2": "Showly",
    "com.mirinae.mirinae": "Mirinae",
    "com.mobilefootie.wc2010": "MobileFootie",
    "com.pandora.android": "Pandora",
    "com.qbis.guessthecountry": "Guess Country",
    "com.rp.hypertrophy": "RP Hypertrophy",
    "com.sbs.diet": "SBS Diet",
    "com.sbs.train": "SBS Train",
    "com.simyasolutions.ling.universal": "Ling Universal",
    "com.snorelab.app": "SnoreLab",
    "com.superchinese": "SuperChinese",
    "com.teslacoilsw.launcher": "Tesla Coil",
    "com.urbandroid.sleep": "Sleep as Android",
    "com.wallpaperscraft.wallpaper": "WallpapersCraft",
    "com.windyty.android": "Windy",
    "com.xodo.pdf.reader": "Xodo PDF",
    "com.zombodroid.MemeGenerator": "Meme Generator",
    "cz.ackee.ventusky": "Ventusky",
    "ginlemon.flowerfree": "FlowerFree",
    "jp.ne.ibis.ibispaintx.app": "ibisPaint X",
    "kr.co.yjteam.dailypay": "DailyPay",
    "kr.eggbun.eggconvo": "EggBun",
    "me.mycake": "MyCake",
    "nom.vrd": "VRD",
    "org.languageapp.lingory": "Lingory",
    "org.totschnig.myexpenses": "My Expenses",
    "com.univision.prendetv": "ViX TV",
    "com.atmfee": "ATM Fee",
    "com.backdrops.wallpapers": "Backdrops",
    "com.llamalab.automate": "Automate",
    "com.nis.app": "NIS",
    "com.noctuasoftware.stellarium_free": "Stellarium",
    "com.proto.circuitsimulator": "Circuit Simulator",
    "com.ttxapps.autosync": "AutoSync",
    "com.ufovpn.connect.velnet": "UFO VPN",
    "com.vitotechnology.StarWalk2Free": "Star Walk 2",
    "com.vitotechnology.sky.tonight.map.star.walk": "Sky Tonight",
    "com.vpn.free.hotspot.secure.vpnify": "VPNify",
    "io.funswitch.blocker": "Blocker",
    "org.zwanoo.android.speedtest": "Speedtest",
    "ai.perplexity.app.android": "Perplexity",
    "all.in.one.calculator": "Calculator",
    "app.rubberbands.fit": "Rubberbands",
    "app.symfonik.music.player": "Symfonik",
    "ch.protonmail.android": "Proton Mail",
    "com.audible.application": "Audible",
    "com.cxinventor.file.explorer": "File Explorer",
    "com.etsy.android": "Etsy",
    "com.gamma.scan": "Gamma Scan",
    "com.kick.mobile": "Kick",
    "com.myvitale.forus": "Forus",
    "com.spocky.projengmenu": "Eng Menu",
    "com.streetwriters.notesnook": "Notesnook",
    "com.thetrainline": "Trainline",
    "org.readera": "ReadEra",
    "photo.editor.photoeditor.photoeditorpro": "Photo Editor Pro",
    "psyberia.alpinequest.free": "AlpineQuest",
    "com.zhiliaoapp.musically": "TikTok",
    "ak.alizandro.smartaudiobookplayer": "Smart AudioBook",
    "altergames.carlauncher": "Car Launcher",
    "app.remux.video.converter": "Video Converter",
    "com.adobe.reader": "Adobe Reader",
    "com.alphaprogression.alphaprogression": "Alpha Progression",
    "com.appfactory.essence": "Essence",
    "com.atomengineapps.teachmeanatomy": "TeachMeAnatomy",
    "com.bandlab.bandlab": "BandLab",
    "com.blockerhero": "BlockerHero",
    "com.budget.tracker_app": "Budget Tracker",
    "com.camerasideas.instashot": "InShot",
    "com.cfdrink": "CF Drink",
    "com.collectrinc.collectr": "Collectr",
    "com.cronometer.android.gold": "Cronometer",
    "com.dv.adm": "ADM",
    "com.finch.finch": "Finch",
    "com.flightradar24free": "Flightradar24",
    "com.google.android.dialer": "Phone",
    "com.hevy": "Hevy",
    "com.hv.replaio": "Replaio",
    "com.maxmpz.audioplayer": "Poweramp",
    "com.naver.linewebtoon": "Webtoon",
    "com.overdevs.at4k": "AT4K",
    "com.paget96.batteryguru": "Battery Guru",
    "com.quizlet.quizletandroid": "Quizlet",
    "com.realbyteapps.moneymanagerfree": "Money Manager",
    "com.rumble.battles": "Rumble",
    "com.soepic.photogallery.release": "Photo Gallery",
    "com.sofascore.results": "Sofascore",
    "com.thehungrywasp.iamsober": "I Am Sober",
    "com.todoist": "Todoist",
    "com.touchtype.swiftkey": "SwiftKey",
    "com.tracked.mobile": "Tracked",
    "com.tranzmate": "Tranzmate",
    "com.tumblr": "Tumblr",
    "com.wanderlog.android": "Wanderlog",
    "com.zenthek.autozen": "AutoZen",
    "currency.converter.moneta": "Moneta",
    "dk.tacit.android.foldersync.lite": "FolderSync",
    "io.stashteam.games.tracker.stashapp": "Stash",
    "net.uniquegem.directchat": "DirectChat",
    "studio.muggle.chatboost": "ChatBoost",
}

# TV packages (armv7 leanback)
TV_PACKAGES: list[str] = [
    "com.netflix.ninja",
    "com.amazon.amazonvideo.livingroom",
    "tv.pluto.android",
    "com.disney.disneyplus",
    "com.wbd.hbomax",
    "com.peacocktv.peacockandroid",
    "com.fox.foxone",
    "com.tubitv",
    "com.bamnetworks.mobile.android.gameday.atbat",
    "com.cbs.ott",
    "com.univision.prendetv",
    "tv.twitch.android.app",  # also has phone variant, TV is separate entry
]

# Clone / package normalization (original -> actual after patch)
CLONE_PACKAGE_MAP: dict[str, str] = {
    "com.mgoogle.android.gms": "app.revanced.android.gms",
    "com.google.android.youtube": "app.morphe.android.youtube",
    "com.google.android.apps.youtube.music": "app.morphe.android.apps.youtube.music",
    "com.chess": "com.chess.prathxm",
}

# Short name collision map for options files (hint -> package)
SHORT_TO_PACKAGE: dict[str, str] = {
    "katana": "com.facebook.katana",
    "orca": "com.facebook.orca",
    "facebook": "com.facebook.katana",
    "messenger": "com.facebook.orca",
}
